### ISSUE TITLE
fail to install plugin

### ISSUE THREAD

**Issue by MMeshkinkiya** [reyery/cea-osm-gwr-mapper#2]
I tried to install this plugin. I was able to clone it, but I'm stuck on the second step: "pip install -e PATH_OF_PLUGIN_FOLDER".
For this command, I copied the following line into the CEA console:
"pip install -e C:\Users\mm\Documents\CityEnergyAnalyst\osm_GWEMapper"
However, I received the error:
"failed to create process."

I also tried to clone the plugin into a different folder (PATH) but still recive same error.

Could you please provide some hints on this matter?
Thank you,
Maryam

**Comment by reyery** [comment]
I was able to install it on my laptop without any problems. I think there might be some issues with with pip in the CEA python environment.

Could you try installing it using the command:
```
python -m pip install -e C:\Users\mm\Documents\CityEnergyAnalyst\osm_GWEMapper
```

**Comment by MMeshkinkiya** [comment]
Thank you Reynold.
It works.
